### ISSUE TITLE
Markup Problems

### ISSUE THREAD

**Issue by artlogic** [arsmentis/volt-docs#22]
* The site has multiple H1 tags - this is probably incorrect given the latest HTML spec. I'm thinking the H1 in the `<nav>` probably shouldn't be an H1.
* `<article>` tags should wrap around `<header>` tags

**Comment by SKBruck** [comment]
This code:
```html
<h1 class="visible-print-block">{{ site.title }}</h1>
```
Is not working anyway, so I just removed it for now. I don't know what you want to do about that. Try printing before you push this change - then let me know how you want to proceed for printing.

**Comment by artlogic** [comment]
I've made a separate issue for printing problems: #26. I think you can close this.
