### ISSUE TITLE
Add links to headers (for easy bookmarking/sharing)

### ISSUE THREAD

**Issue by artlogic** [arsmentis/volt-docs#32]
There's got to be a JS or Jekyll plugin to do this. Example: https://docs.python.org/3/library/stdtypes.html#string-methods

**Comment by SKBruck** [comment]
I will need more help/clarification with this than is available on your link.

**Comment by artlogic** [comment]
However over the linked header. Notice the link/symbol that appears? Sometimes a `#` is used instead.

**Comment by SKBruck** [comment]
Ok, thank you - I should be able to find a plugin to do that.

**Comment by SKBruck** [comment]
This is the current look of the header links. Do you want the link symbol to appear on hover only like on jekyll docs?

![current-header-links](https://cloud.githubusercontent.com/assets/2489779/22236689/3dabca48-e1d5-11e6-95d7-fee917cbf157.png)

**Comment by SKBruck** [comment]
Here's what it looks like with the hover:
![header-link-hover](https://cloud.githubusercontent.com/assets/2489779/22237109/ad43403c-e1d7-11e6-90f4-67c8cea6e5dd.png)
