### ISSUE TITLE
Make inline code blocks look more like fenced code blocks

### ISSUE THREAD

**Issue by artlogic** [arsmentis/volt-docs#33]
Take a look at this page:

https://docs.voltcloud.io/getting-started/handling-errors/

Notice the fenced/tabbed code blocks have a very different look than the inline code blocks. Let's try and get them more into parity.

**Comment by SKBruck** [comment]
The css to change this is in the custom bootstrap theme. Before I go around messing about with that, do you want the text color to stay orange or do you want me to change it? (See screenshots)

Getting a border around the inline code blocks is proving difficult.

![black-text](https://cloud.githubusercontent.com/assets/2489779/22180025/246970a2-e032-11e6-994e-e516f8ccef49.png)
![orange-text](https://cloud.githubusercontent.com/assets/2489779/22180024/246945d2-e032-11e6-96ff-5342360919df.png)

**Comment by artlogic** [comment]
Don't worry about the border. I say the first screenshot is good enough, unless you have any objections (or @nsbasic has objections).
